# Generated by Django 3.2 on 2022-12-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaryapp', '0006_remove_barbermodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assingmentmodel',
            name='tip',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='prize',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
